database:
  type: MYSQL
  url: 127.0.0.1
  port: 3306
  databasename: safecity
  username: username
  password: password

general:
  min-zone-distance: 50
  max-zones-per-player: 1
  wilderness-pvp: false

allowed-worlds:
  - world
  - world_nether

prices:
  public-zone: 15000
  public-spawn: 7500
  pvp-zone: 1000