name: SafeCity
main: me.jayfella.SafeCity.SafeCityPlugin
version: 1.0.6
author: jayfella
depend: [ Vault, c3p0Extension ]

commands:
    zone:
        aliases: [z]
    citizen:
        aliases: [cz]
    family:
        aliases: [fam]

permissions:
    safecity.public.create:
        description: Allows a player to create a primary zone.
        default: true

    safecity.public.delete:
        description: Allow a player to delete a primary zone with paying residents still in the zone.
        default: false

    safecity.staff:
        description: Staff override
        default: op